### ISSUE TITLE
Tables in markdown preview will be affected

### ISSUE THREAD

**Issue by Phisherman** [silvestreh/atom-material-syntax#15]
If I use this syntax theme, the markdown preview's table header will be affected.
![](http://share.phishy.de/kK-gJZ9Ncfb03054a5625c56aa40e44685da0e0d.png)

I use atom-material-syntax version `0.2.3`.

There is the following rule who change the background color but it doesn't change the font color.
```css
.markdown-preview table th {
  background-color: #364850;
}
```
